services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3002:3002
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      DATABASE_URL: postgresql://postgres:example@db:5432/postgres
    depends_on:
      - db

  db:
    image: postgres:17
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  postgres_data:
